import os
import logging

# Lazy-import ElevenLabs inside the synth function to avoid import-time failures
# on machines without the ElevenLabs SDK installed.

logger = logging.getLogger(__name__)

# Predefined voice IDs for the interviewer personas from ElevenLabs library
# You can use standard default voices:
# - Alex (Tech Lead, Analytical, Direct) -> "Josh" voice (pNInz6obpgq5qcGbe82y)
# - Sarah (Recruiter, Friendly, STAR focus) -> "Rachel" voice (21m00Tcm4TlvDq8ikWAM)
# - Marcus (Director, Authoritative, Strategy) -> "Marcus" voice (IKne3meq5aSn9XLyUdCD)
PERSONA_VOICES = {
    "alex": {
        "voice_id": "pNInz6obpgq5qcGbe82y",
        "stability": 0.45,
        "similarity_boost": 0.70,
        "description": "Direct, fast-paced technical interviewer voice"
    },
    "sarah": {
        "voice_id": "21m00Tcm4TlvDq8ikWAM",
        "stability": 0.75,
        "similarity_boost": 0.85,
        "description": "Warm, encouraging talent partner voice"
    },
    "marcus": {
        "voice_id": "N2lVS1wkeJe5zZ1tWkry",  # Standard deep male voice
        "stability": 0.60,
        "similarity_boost": 0.80,
        "description": "Calm, deliberate executive director voice"
    }
}

def synthesize_persona_voice(text: str, persona: str) -> bytes | None:
    """
    Synthesizes text into audio bytes using ElevenLabs API.
    Returns audio bytes if successful, or None if key is missing/error occurs.
    """
    api_key = os.environ.get("ELEVEN_LABS_API_KEY")
    if not api_key:
        logger.warning("ELEVEN_LABS_API_KEY environment variable not found. Requesting browser speech fallback.")
        return None

    # Normalise persona
    p_key = persona.lower().strip()
    if p_key not in PERSONA_VOICES:
        p_key = "sarah"  # Default fallback

    voice_config = PERSONA_VOICES[p_key]

    try:
        # Lazy import to avoid raising ImportError at module import time
        try:
            from elevenlabs.client import ElevenLabs
        except Exception as ie:
            logger.warning(f"ElevenLabs SDK not available: {ie}. Falling back to browser TTS.")
            return None

        # Initialize ElevenLabs client
        client = ElevenLabs(api_key=api_key)

        # Generate speech
        audio_generator = client.generate(
            text=text,
            voice=voice_config["voice_id"],
            model="eleven_monolingual_v1",  # Low-latency model
        )

        # Collect generated bytes
        audio_bytes = b"".join(list(audio_generator))
        return audio_bytes

    except Exception as e:
        logger.error(f"ElevenLabs voice synthesis failed: {e}. Falling back.")
        return None
